dist: focal
language: ruby
sudo: false
arch:
  - amd64
  - ppc64le
services:
  - mongodb
addons:
  postgresql: "13"
gemfile:
  - Gemfile
  - Gemfile.rails60
  - Gemfile.rails61
  - Gemfile.mongo_mapper
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1
before_install:
  - gem install bundler
env:
  global:
    - DB_USER=postgres
    - DB_PASS=
    - DB_USER=postgres
      arch: ppc64le
    - DB_PASS=
      arch: ppc64le
  
  matrix:
    - DB=sqlite3
    - DB=postgresql
matrix:
  fast_finish: true
  exclude:
    - gemfile: Gemfile.mongo_mapper
      env: DB=postgresql
    - gemfile: Gemfile.mongo_mapper
      arch: ppc64le
      env: DB=postgresql

branches:
  only:
    - master
notifications:
  email: false
